### PR TITLE
Detailed landing page

### PR DESCRIPTION
**Pull request by Mohitkumar33**
done the local storage part to save the tasks

### CODE REVIEW

**Review by aqsaaqeel — APPROVED** [review]
I really like how your landing page is a separate component. You can put a screenshot of the extension to see

**Comment by Mohitkumar33** [comment]
sure aqsaaqeel

**Review by RakshithBhat03 — APPROVED** [review]
- The code looks clean and well structured. 
- Suggestion: You could provide a screenshot or preview for future PR's.

**Comment by Mohitkumar33** [comment]
Its deployed at        https://focus-extension.netlify.app/             but not merged the current changes

**Pull request merged**
